<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Minha Página Pessoal</title>
    <link rel="stylesheet" href="styles.css"> <!-- Opcional: link para um arquivo CSS -->
</head>
<body>
    <header>
        <h1>Bem-vindo à Minha Página Pessoal</h1>
        <nav>
            <ul>
                <li><a href="#home">Home</a></li>
                <li><a href="#sobre">Sobre</a></li>
                <li><a href="#contato">Contato</a></li>
            </ul>
        </nav>
    </header>
    
    <main>
        <section id="sobre">
            <h2>Sobre Mim</h2>
            <p>Olá! Eu sou [Seu Nome] e este é um pequeno resumo sobre mim.</p>
            <h3>Meus Hobbies:</h3>
            <ul>
                <li>Leitura</li>
                <li>Esportes</li>
                <li>Programação</li>
            </ul>
            <img src="sua-imagem.jpg" alt="Uma imagem minha">
        </section>
    </main>
    
    <footer>
        <p>Entre em contato: meuemail@example.com</p>
        <p>Redes sociais: [Links para suas redes sociais]</p>
    </footer>
</body>
</html>
